语法上，允许析构函数抛出异常。但是，析构函数抛出异常，经常会带来一些问题。

什么问题呢？

有两个问题，一是析构函数异常点之后的代码得不到执行，可能造成释放资源的语言得不到执行，这是会造成资源泄露；二是C++在异常传播过程会进行栈展开，即退出复合语句和函数的过程。在栈展开过程会调用已经在栈中构造好的对象的析构函数来释放资源，如果此时遇到异常，则前一个异常未处理，又遇到一个新的异常，此时程序会奔溃。

如果析构函数必须执行一个动作，而该动作可能会在失败时抛出异常，该怎么办？Effective C++中给出了三种解决方案，再次感叹真是一本好书，尽管我们可能没遇到过析构函数抛出异常的棘手情况（所以印象不深刻，突然被问到可能会懵），但是书中的描述总有一种让我们身临其境的感受。

注意，不要抛出异常，不是说不可以出现异常，如果析构函数中出现异常，使用try catch捕获了异常，此时就没有抛出。

忘记了就看看Effective C++第三版的条款8吧：不要让异常逃离析构函数。